# Generated by Django 4.2.30 on 2026-08-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_chapter_course_exam_lesson_alter_contest_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='judge.lesson', verbose_name='lesson'),
        ),
        migrations.CreateModel(
            name='LessonProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, help_text='Để trống nếu muốn sử dụng tên gốc của bài tập.', max_length=255, verbose_name='Tên bài hiển thị tùy biến')),
                ('custom_score', models.FloatField(blank=True, help_text='Điểm tối đa cho bài tập trong khuôn khổ bài học này.', null=True, verbose_name='Điểm số tùy biến')),
                ('is_required_for_completion', models.BooleanField(default=False, help_text='Nếu bật, học viên bắt buộc phải AC bài này mới có thể hoàn thành bài học.', verbose_name='Bắt buộc hoàn thành (AC)')),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_problems', to='judge.lesson', verbose_name='Bài học')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_lessons', to='judge.problem', verbose_name='Bài tập kho VNOJ')),
            ],
            options={
                'verbose_name': 'Bài tập đính kèm bài học',
                'verbose_name_plural': 'Các bài tập đính kèm bài học',
                'ordering': ('order_index', 'id'),
                'unique_together': {('lesson', 'problem')},
            },
        ),
    ]
