# Generated by Django 4.2.30 on 2026-08-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0233_submission_lesson_lessonproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Khi khóa, học viên không thể truy cập học hay làm bài.', verbose_name='Khóa khóa học'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Học phí của khóa học (0 đồng là Miễn phí).', verbose_name='Học phí (VNĐ)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Khi khóa, chỉ giáo viên mới có thể xem, học viên không thể truy cập.', verbose_name='Khóa kỳ thi'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Khi khóa, chỉ giáo viên mới có thể xem, học viên không thể truy cập.', verbose_name='Khóa bài học'),
        ),
    ]
