# Generated by Django 4.2.30 on 2026-08-19 02:55

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0234_course_is_locked_course_price_exam_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_province_contest',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Provincial contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='province',
            field=models.CharField(blank=True, choices=[('AG', _('An Giang')),
    ('BN', _('Bắc Ninh')),
    ('CM', _('Cà Mau')),
    ('CB', _('Cao Bằng')),
    ('DL', _('Đắk Lắk')),
    ('DB', _('Điện Biên')),
    ('DT', _('Đồng Tháp')),
    ('GL', _('Gia Lai')),
    ('HT', _('Hà Tĩnh')),
    ('HY', _('Hưng Yên')),
    ('KH', _('Khánh Hoà')),
    ('LC', _('Lai Châu')),
    ('LS', _('Lạng Sơn')),
    ('LCA', _('Lào Cai')),
    ('LD', _('Lâm Đồng')),
    ('NA', _('Nghệ An')),
    ('NB', _('Ninh Bình')),
    ('PT', _('Phú Thọ')),
    ('QNG', _('Quảng Ngãi')),
    ('QNI', _('Quảng Ninh')),
    ('QT', _('Quảng Trị')),
    ('SL', _('Sơn La')),
    ('TN', _('Tây Ninh')),
    ('TNG', _('Thái Nguyên')),
    ('TH', _('Thanh Hóa')),
    ('CT', _('TP. Cần Thơ')),
    ('DN', _('TP. Đà Nẵng')),
    ('DNA', _('TP. Đồng Nai')),
    ('HN', _('TP. Hà Nội')),
    ('HP', _('TP. Hải Phòng')),
    ('HCM', _('TP. Hồ Chí Minh')),
    ('HUE', _('TP. Huế')),
    ('TQ', _('Tuyên Quang')),
    ('VL', _('Vĩnh Long'))], db_index=True, default='', max_length=10, verbose_name='Province/City'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='end time'),
        ),
    ]
