# Generated by Django 4.2.30 on 2026-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0236_contest_province_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_self_enrollment',
            field=models.BooleanField(db_index=True, default=True, help_text='Cho phép học viên tự bấm Đăng ký. Nếu tắt, chỉ giảng viên mới có thể thêm học viên.', verbose_name='Cho phép tự đăng ký'),
        ),
        migrations.AddField(
            model_name='course',
            name='contact_url',
            field=models.CharField(blank=True, default='', help_text='Đường dẫn mở khi học viên bấm "Liên hệ đăng ký" (cho khóa học tốn phí).', max_length=512, verbose_name='Link Facebook / Tư vấn đăng ký'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_info',
            field=models.CharField(blank=True, default='12 tuần (24 buổi)', max_length=128, verbose_name='Thời lượng học'),
        ),
        migrations.AddField(
            model_name='course',
            name='format_type',
            field=models.CharField(blank=True, default='Online qua Zoom', max_length=64, verbose_name='Hình thức học'),
        ),
        migrations.AddField(
            model_name='course',
            name='reg_status',
            field=models.CharField(choices=[('OPEN', 'Đang mở đăng ký'), ('UPCOMING', 'Sắp khai giảng'), ('CLOSED', 'Hết chỗ / Đóng đăng ký')], db_index=True, default='OPEN', max_length=16, verbose_name='Trạng thái tuyển sinh'),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_info',
            field=models.CharField(blank=True, default='Tối T3, T5 (19h30 - 21h30)', max_length=255, verbose_name='Lịch học'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.CharField(blank=True, default='Khối THPT', max_length=128, verbose_name='Đối tượng / Khối lớp'),
        ),
        migrations.AddField(
            model_name='course',
            name='validity_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Thời gian học tính bằng ngày kể từ mốc ghi danh. Để trống nếu không giới hạn.', null=True, verbose_name='Thời hạn học (ngày)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Ngày hết hạn truy cập'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang học'), ('READY_FOR_REVIEW', 'Chờ duyệt cấp chứng chỉ'), ('COMPLETED', 'Đã hoàn thành / Nhận chứng chỉ'), ('DROPPED', 'Đã hủy'), ('EXPIRED', 'Đã hết hạn')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
