# Generated by Django 4.2.30 on 2026-08-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0237_course_allow_self_enrollment_course_contact_url_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='contest',
                    name='is_province_contest',
                ),
                migrations.RemoveField(
                    model_name='contest',
                    name='province',
                ),
                migrations.RemoveField(
                    model_name='contest',
                    name='province_category',
                ),
                migrations.AddField(
                    model_name='course',
                    name='start_date_info',
                    field=models.CharField(blank=True, default='15/09/2026', max_length=128, verbose_name='Ngày khai giảng'),
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='ProvinceExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Ví dụ: Đề thi chọn HSG lớp 12 tỉnh Ninh Bình năm học 2023 - 2024', max_length=255, verbose_name='Tên đề / Kỳ thi')),
                ('category', models.CharField(choices=[('thpt', 'Đề thi HSG THPT'), ('thcs', 'Đề thi HSG THCS'), ('tieu_hoc', 'Đề thi Tiểu học'), ('chuyen', 'Kỳ thi Chuyên'), ('olympic', 'Olympic / Trại hè'), ('hsgqg', 'HSG Quốc gia / TST'), ('other', 'Đề thi Khác')], db_index=True, default='thpt', max_length=20, verbose_name='Cấp học / Loại đề')),
                ('province', models.CharField(blank=True, choices=[('ALL', 'Toàn quốc'), ('AG', 'An Giang'), ('BV', 'Bà Rịa - Vũng Tàu'), ('BL', 'Bạc Liêu'), ('BG', 'Bắc Giang'), ('BK', 'Bắc Kạn'), ('BN', 'Bắc Ninh'), ('BTR', 'Bến Tre'), ('BD', 'Bình Định'), ('BDU', 'Bình Dương'), ('BP', 'Bình Phước'), ('BT', 'Bình Thuận'), ('CM', 'Cà Mau'), ('CT', 'Cần Thơ'), ('CB', 'Cao Bằng'), ('DN', 'Đà Nẵng'), ('DL', 'Đắk Lắk'), ('DNO', 'Đắk Nông'), ('DB', 'Điện Biên'), ('DNA', 'Đồng Nai'), ('DT', 'Đồng Tháp'), ('GL', 'Gia Lai'), ('HG', 'Hà Giang'), ('HNA', 'Hà Nam'), ('HN', 'Hà Nội'), ('HT', 'Hà Tĩnh'), ('HD', 'Hải Dương'), ('HP', 'Hải Phòng'), ('HGI', 'Hậu Giang'), ('HB', 'Hòa Bình'), ('HY', 'Hưng Yên'), ('KH', 'Khánh Hòa'), ('KG', 'Kiên Giang'), ('KT', 'Kon Tum'), ('LC', 'Lai Châu'), ('LD', 'Lâm Đồng'), ('LS', 'Lạng Sơn'), ('LCA', 'Lào Cai'), ('LA', 'Long An'), ('ND', 'Nam Định'), ('NA', 'Nghệ An'), ('NB', 'Ninh Bình'), ('NT', 'Ninh Thuận'), ('PT', 'Phú Thọ'), ('PY', 'Phú Yên'), ('QB', 'Quảng Bình'), ('QNA', 'Quảng Nam'), ('QNG', 'Quảng Ngãi'), ('QNI', 'Quảng Ninh'), ('QT', 'Quảng Trị'), ('ST', 'Sóc Trăng'), ('SL', 'Sơn La'), ('TN', 'Tây Ninh'), ('TB', 'Thái Bình'), ('TNG', 'Thái Nguyên'), ('TH', 'Thanh Hóa'), ('HUE', 'Thừa Thiên Huế'), ('TG', 'Tiền Giang'), ('HCM', 'TP. Hồ Chí Minh'), ('TV', 'Trà Vinh'), ('TQ', 'Tuyên Quang'), ('VL', 'Vĩnh Long'), ('VP', 'Vĩnh Phúc'), ('YB', 'Yên Bái')], db_index=True, default='', max_length=10, verbose_name='Tỉnh / Thành phố')),
                ('academic_year', models.CharField(db_index=True, help_text='Ví dụ: 2023 - 2024 hoặc 2024', max_length=32, verbose_name='Năm học / Năm tổ chức')),
                ('exam_url', models.URLField(blank=True, default='', help_text='Đường dẫn tải hoặc xem trực tuyến file đề thi (PDF, Google Drive, OneDrive, v.v.).', max_length=1000, verbose_name='Link đề thi (PDF / Drive)')),
                ('solution_url', models.URLField(blank=True, default='', help_text='Đường dẫn tải hoặc xem đáp án, lời giải chi tiết, file test.', max_length=1000, verbose_name='Link lời giải / Bộ test')),
                ('practice_url', models.URLField(blank=True, default='', help_text='Đường dẫn luyện tập khác nếu không dùng Contest trên hệ thống.', max_length=1000, verbose_name='Link luyện tập ngoài')),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Có hiển thị card này trên trang danh sách đề thi hay không (mặc định: Có).', verbose_name='Hiển thị card')),
                ('description', models.TextField(blank=True, help_text='Thông tin thêm về cấu trúc đề, thang điểm, thời gian làm bài, v.v.', verbose_name='Ghi chú / Mô tả tóm tắt')),
                ('order', models.IntegerField(default=0, help_text='Số càng lớn sẽ được ưu tiên hiển thị trước.', verbose_name='Thứ tự ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('contest', models.ForeignKey(blank=True, help_text='Chọn Contest trên hệ thống để người học vào làm bài trực tiếp.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_exams', to='judge.contest', verbose_name='Kỳ thi luyện tập (Contest)')),
            ],
            options={
                'verbose_name': 'Đề thi Tỉnh / Thành phố',
                'verbose_name_plural': 'Kho lưu trữ Đề thi Tỉnh / Thành phố',
                'ordering': ['-order', '-academic_year', '-created_at'],
            },
        ),
    ]
