# Generated by Django 4.2.30 on 2026-08-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0238_remove_contest_is_province_contest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(db_index=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='provinceexam',
            name='academic_year',
            field=models.CharField(db_index=True, help_text='Định dạng cụ thể: 2025-2026, 2024-2025, 2023-2024...', max_length=16, verbose_name='Năm học'),
        ),
        migrations.AlterField(
            model_name='provinceexam',
            name='category',
            field=models.CharField(choices=[('thpt', 'THPT'), ('thcs', 'THCS'), ('chuyen', 'Thi Chuyên'), ('olympic', 'Olympic / Trại hè'), ('hsgqg', 'Đội tuyển HSGQG')], db_index=True, default='thpt', max_length=20, verbose_name='Cấp học / Loại đề'),
        ),
        migrations.AlterField(
            model_name='provinceexam',
            name='name',
            field=models.CharField(db_index=True, help_text='Ví dụ: Đề thi chọn HSG lớp 12 tỉnh Ninh Bình năm học 2025-2026', max_length=255, verbose_name='Tên đề / Kỳ thi'),
        ),
    ]
