# Generated by Django 4.2.30 on 2026-09-03 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0242_course_instructors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_info',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Thời lượng học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='format_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Hình thức học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule_info',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lịch học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date_info',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Ngày khai giảng'),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_audience',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Đối tượng / Khối lớp'),
        ),
        migrations.AlterField(
            model_name='coursecontest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.PositiveIntegerField(default=1048576, help_text='The memory limit for this problem, in kilobytes (e.g. 64mb = 65536 kilobytes).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1048576)], verbose_name='memory limit'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.FloatField(default=1.0, help_text="Points awarded for problem completion. Points are displayed with a 'p' suffix if partial.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=1.0, help_text='The time limit for this problem, in seconds. Fractional seconds (e.g. 1.5) are supported.', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(60)], verbose_name='time limit'),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[('vi', 'Vietnamese')], max_length=7, verbose_name='language'),
        ),
    ]
