# Generated by Django 4.2.30 on 2026-08-28 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICPCRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('student_id', models.CharField(max_length=50, verbose_name='Mã sinh viên')),
                ('academic_class', models.CharField(max_length=100, verbose_name='Lớp')),
                ('cohort', models.CharField(max_length=50, verbose_name='Khóa (ví dụ: K71, K72, K73...)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại (Zalo)')),
                ('facebook_url', models.CharField(blank=True, max_length=255, verbose_name='Link Facebook')),
                ('programming_experience', models.CharField(choices=[('beginner', 'Mới bắt đầu học lập trình'), ('basic', 'Đã nắm cơ bản (C++, Python, Pascal...)'), ('intermediate', 'Đã học Cấu trúc dữ liệu & Thuật toán'), ('advanced', 'Đã tham gia đội tuyển / HSG / Olympic / ICPC')], default='beginner', max_length=50, verbose_name='Trình độ lập trình')),
                ('achievements', models.TextField(blank=True, verbose_name='Thành tích / Kinh nghiệm / Giải thưởng đã đạt được')),
                ('reason', models.TextField(verbose_name='Lý do & Mục tiêu tham gia')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái duyệt')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú của Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng ký')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icpc_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản HNUEOJ')),
            ],
            options={
                'verbose_name': 'Đơn đăng ký ICPC',
                'verbose_name_plural': 'Danh sách đơn đăng ký ICPC',
                'ordering': ['-created_at'],
            },
        ),
    ]
