# Generated by Django 4.2.30 on 2026-08-22 10:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.CharField(help_text='Mã học kỳ (VD: 2023_2024_HK1)', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tên học kỳ')),
                ('academic_year', models.CharField(help_text='VD: 2023-2024', max_length=20, verbose_name='Năm học')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Thứ tự kỳ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Danh sách học kỳ',
                'ordering': ['academic_year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Mã học phần')),
                ('name', models.CharField(max_length=255, verbose_name='Tên môn học')),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Số tín chỉ')),
                ('department', models.CharField(blank=True, max_length=150, null=True, verbose_name='Khoa / Bộ môn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Danh mục môn học',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(choices=[('A', 'A (4.0) - Giỏi / Xuất sắc'), ('B+', 'B+ (3.5) - Khá giỏi'), ('B', 'B (3.0) - Khá'), ('C+', 'C+ (2.5) - Trung bình khá'), ('C', 'C (2.0) - Trung bình'), ('D+', 'D+ (1.5) - Trung bình yếu'), ('D', 'D (1.0) - Đạt'), ('F', 'F (0.0) - Không đạt (Học lại)')], max_length=5, verbose_name='Điểm chữ')),
                ('score_4', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3, verbose_name='Điểm hệ 4')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student_profile.semester', verbose_name='Học kỳ')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='student_profile.subject', verbose_name='Môn học')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_grades', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản sinh viên')),
            ],
            options={
                'verbose_name': 'Điểm sinh viên',
                'verbose_name_plural': 'Bảng điểm sinh viên',
                'ordering': ['-semester__academic_year', '-semester__order', 'subject__code'],
                'unique_together': {('user', 'semester', 'subject')},
            },
        ),
    ]
