# Generated by Django 4.2.30 on 2026-08-22 10:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['academic_year', 'order', 'created_at'], 'verbose_name': 'Học kỳ', 'verbose_name_plural': 'Danh sách học kỳ'},
        ),
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'ordering': ['semester__academic_year', 'semester__order', 'order', 'created_at'], 'verbose_name': 'Điểm sinh viên', 'verbose_name_plural': 'Bảng điểm sinh viên'},
        ),
        migrations.AddField(
            model_name='semester',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_semesters', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo (null nếu là kỳ mặc định)'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='improvement_grade',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Điểm cải thiện'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='target_grade',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Mục tiêu'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='academic_year',
            field=models.CharField(default='2023-2024', max_length=30, verbose_name='Năm học'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.CharField(help_text='Mã học kỳ (VD: 2023_2024_HK1, sem_1, ...)', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Tên học kỳ'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (4.0)'), ('A', 'A (3.7 / 4.0)'), ('B+', 'B+ (3.5)'), ('B', 'B (3.0)'), ('C+', 'C+ (2.5)'), ('C', 'C (2.0)'), ('D+', 'D+ (1.5)'), ('D', 'D (1.0)'), ('F', 'F (0.0)')], max_length=5, null=True, verbose_name='Điểm hiện tại'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='score_4',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=4, verbose_name='Điểm hệ 4'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã học phần'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Số tín chỉ'),
        ),
    ]
