# Generated by Django 4.2.30 on 2026-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_alter_semester_options_alter_studentgrade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=30, verbose_name='Năm học'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.CharField(help_text='Mã học kỳ (VD: 2025_2026_HK1, sem_1, ...)', max_length=50, primary_key=True, serialize=False),
        ),
    ]
