# Generated by Django 4.2.30 on 2026-08-22 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_alter_semester_academic_year_alter_semester_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Độ khó môn học (1-10)'),
        ),
    ]
